In [1]:
import numpy as np
import pandas as pd

In [23]:
arr = np.random.randint(0,5,(5,5))

In [24]:
arr

array([[3, 3, 1, 3, 3],
       [1, 0, 1, 1, 2],
       [0, 2, 2, 0, 4],
       [0, 0, 4, 1, 3],
       [0, 1, 4, 3, 3]])

In [25]:
print(arr.mean(axis = 0))
print(arr.std(axis = 0))
print(arr.var(axis = 0))

[0.8 1.2 2.4 1.6 3. ]
[1.16619038 1.16619038 1.356466   1.2        0.63245553]
[1.36 1.36 1.84 1.44 0.4 ]


In [28]:
b = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [42]:
b = np.array(b)
print(b.argsort())
print(b.dtype)
print(b.shape)
print(type(b))
print(b.reshape(int(input("Enter the rows")), int(input("Enter the columns"))))

[8 2 6 9 3 7 1 0 4 5]
int32
(10,)
<class 'numpy.ndarray'>
[[56 48 22 41 78]
 [91 24 46  8 33]]


In [132]:
arr = np.random.randint(0, 10, (5, 5))
arr = arr.astype("float")
arr = arr.flatten()
arr[np.random.choice(arr.size,3 ,False)] = np.nan
arr = arr.reshape(5,5)
arr

array([[ 3., nan,  7.,  1.,  6.],
       [ 3.,  7.,  0.,  1.,  5.],
       [ 4.,  6., nan,  1.,  9.],
       [ 7.,  4.,  9.,  6.,  4.],
       [ 5., nan,  9.,  8.,  1.]])

In [143]:
zero = np.argwhere( arr == 0)
non_zero = np.argwhere( arr != 0)
nan = np.argwhere(np.isnan(arr)) 